### ISSUE TITLE
Error: java.lang.NoClassDefFoundError: org/mozilla/javascript/WrapFactory

### ISSUE THREAD

**Issue by GrahamHannington** [robander/svg-syntaxdiagrams#3]
I'm resurrecting this issue, and this original version of this comment because, as per issue #4, it turns out what I did here should have worked (no build step required)...

With apologies if this is a DITA-OT newbie problem, and nothing to do with these particular plugins...
it's been years since I've installed DITA-OT (at work, I use an IBM-provided toolchain)...

I'm using Windows 10.

I installed DITA 2.5.4 (2.5 is the DITA-OT version cited in the readme of this repo).

I downloaded this repo as a .zip that I unzipped into the `dita-ot-2.5.4\plugins` directory, which added these plugin subdirectories:

```
com.ibm.ditatools.svg-diagrams
com.moldflow.dita.plus-allhtml-svgobject
com.moldflow.dita.plus-allhtml-syntaxdiagram
com.moldflow.dita.plus-allhtml-syntaxdiagram-svgobject
com.moldflow.dita.plus-html-topics-twopass
com.moldflow.dita.svgobject
com.moldflow.dita.syntaxdiagram.consolidated
com.moldflow.dita.syntaxdiagram2svg
org.apache.xmlgraphics.batik
```

I ran this DITA-OT command:

```
dita -install
```

I created a test DITA topic in the Oxygen XML editor:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE topic PUBLIC "-//OASIS//DTD DITA Topic//EN" "topic.dtd">
<topic id="svg-syntax-diagram">
<title>SVG syntax diagram</title>
<body>
<syntaxdiagram>
<groupseq>
<kwd>COMMAND</kwd>
<groupchoice importance="optional">
<repsep>,</repsep>
<kwd importance="default">OPTIONA</kwd>
<kwd>OPTIONB</kwd>
<kwd>OPTIONC</kwd>
</groupchoice>
</groupseq>
</syntaxdiagram>
</body>
</topic>
```

I ran this DITA command:

```
dita -input=svg-syntax-diagram.dita -format=html5
```

I got this error:

```
Error: java.lang.NoClassDefFoundError: org/mozilla/javascript/WrapFactory
```

Excerpts from running the same command with a `-d` option:

```
Detected Java version: 1.8 in: C:\Program Files\Java\jdk1.8.0_191\jre
...
[available] Unable to load class org.apache.crimson.parser.XMLReaderImpl
[available] Unable to load class net.sf.saxon.StyleSheet
...
```

I can format this sample topic without error:

```
dita -input=sequence.ditamap -format=html5
```

Any ideas? `classpath` issue? How do I fix it?

**Comment by GrahamHannington** [comment]
I fixed the problem by downloading a binary release of [Rhino](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/Rhino), and copying the `rhino-1.7.9.jar` file to the `dita-ot-2.5.4\lib` directory.

**Comment by robander** [comment]
Not sure what caused this - I was only ever able to reproduce the error by deleting the Rhino code that was stored within the Batik library.

Regardless - the latest code in `develop` now includes update #14 which should resolve this - it does away with most of the extra Batik files, ships Rhino (`js.jar`) inside the plugin that needs it, and ensures that `js.jar` is integrated into the classpath as it would have been inside `dita-ot/lib/`
