### ISSUE TITLE
Why does the SVG contain references to scripts?

### ISSUE THREAD

**Issue by GrahamHannington** [robander/svg-syntaxdiagrams#5]
The output SVG contains numerous relative path references to JavaScript files:

```javascript
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/constants.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/diagram.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/sequence.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/loop.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/decision.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/revdecision.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/boxed.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/unboxed.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/text.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/void.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/notecontainer.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/note.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
<svg:script xmlns="http://www.w3.org/1999/xhtml" type="text/ecmascript" xlink:href="../js/syntaxdiagram-svg/main.js" xlink:type="simple" xlink:actuate="onLoad" xlink:show="other"/>
```

However, `-format=html5` does not copy such files to the output. So, when I view an SVG syntax diagram in a web browser, the browser console contains a "file not found" error for each of these script files.

I can see most of the required script files (or at least, files with those names)—with the notable exception of `constants.svg`—in `com.moldflow.dita.syntaxdiagram2svg\js`. I tried copying those files to the relative path expected by the SVG. In addition to the expected remaining error:

    GET [...]/syntaxdiagram-svg/constants.js net::ERR_FILE_NOT_FOUND

I got numerous errors about `syntaxdiagram_Dispatch` being undefined:

    diagram.js:3 Uncaught ReferenceError: syntaxdiagram_Dispatch is not defined at diagram.js:3

The documentation in `com.moldflow.dita.syntaxdiagram2svg\doc\reference.xml` states that `com.moldflow.dita.syntaxdiagram2svg\xsl\make-constants.xsl` transforms `com.moldflow.dita.syntaxdiagram2svg\resource\constants.xml` into `constants.js`—or should do—but I haven't gone looking any further; I decided to write this issue instead.

I notice that the documentation in `reference.xml` refers to "dynamic SVG".

The "static" SVG syntax diagrams seem (to me) to render just fine in my web browser without those script files (setting aside the browser console errors about the missing files). So... are they required? I've only looked at them briefly, so I'm probably completely wrong about this, but they seem to contain code to dynamically generate the SVG that the static SVG output file already contains.

And: if they're required (which they don't seem to be), then that's going to be a problem for formatting environments such as [Antenna House Formatter 6.5](https://www.antennahouse.com/product/ahf65/ahf-svg.html#SVG-conformance) that don't support `<script>` elements in SVG, right?

Why does the SVG contains those references to `<script>` elements?

Can you offer more details about the "dynamic SVG" mentioned in `reference.xml`?

Have I overlooked some documentation that describes all of this?

**Comment by GrahamHannington** [comment]
I tried commenting-out some of the "arrowHead" calls in those JavaScript files and, sure enough, the corresponding arrowheads did not appear in the output SVG. So I'm making some progress (baby steps) at understanding how this plugin works, and also at customizing the appearance of the output.

My original question about why those `<script>` elements are in the _static_ SVG output remains.

**Comment by robander** [comment]
Hi Graham.

The documentation you've found is the only documentation available; it's the documentation that Deborah provided with the original version of the plugins.

The JavaScript is evaluated by Batik (well, Rhino, within Batik) as part of the relatively convoluted path from DITA markup to SVG markup + batik to static SVG. I have not done anything to add or remove the JS references along the path, and they should not cause any problems, so I do not expect to change this (thus the closing of this ticket).

FYI I have been doing a lot of investigation into the arrows, with some small amount of progress, but nothing that I'm really able to share or post at this point. As it stands right now, every arrow in the diagram is generated using exactly the same JS function, resulting in exactly the same CSS class, so simply turning the arrows on/off (in the JS or in the CSS) will remove both the arrows critical that you do want as well as the arrows that you do not want.

**Comment by GrahamHannington** [comment]
Hi @robander,

You wrote:

> simply turning the arrows on/off (in the JS or in the CSS) will remove both the arrows critical that you do want as well as the arrows that you do not want.

Really? See the (counter)example diagram under the heading "Example with some of my suggested changes" in my recent comment on issue #2. As described in that comment, I created that diagram by selectively commenting-out calls in the JavaScript to the function that draws the arrowheads (here, I'm deliberately using the specific term "arrowheads", not arrows). That has _not_ removed the "critical" arrowheads that I want to keep.
